#
# Copyright 2022 Anysphere, Inc.
# SPDX-License-Identifier: GPL-3.0-only
#

filegroup(
    name = "asphr-release",
    srcs = [
        "//client/cli:asphr",
        "//client/daemon:main",
    ],
)
