#!/usr/bin/env bash

#
# Copyright 2022 Anysphere, Inc.
# SPDX-License-Identifier: MIT
#

# postinstall is run in the Mac .pkg after the installation has gone through
# here we set up the daemon!
# we also link the CLI to /usr/local/bin

create_user_dir() {
	install -d -o "$USER" -g "$(id -g "$USER")" "$1"
}

LOG_DIR=""
# set to XDG_CACHE_HOME/logs if it exists, otherwise use .anysphere directory as always
if [ -d "${XDG_CACHE_HOME}" ]; then
	LOG_DIR="${XDG_CACHE_HOME}/anysphere/logs"
	create_user_dir "${XDG_CACHE_HOME}/anysphere"
	create_user_dir "${XDG_CACHE_HOME}/anysphere/logs"
else
	LOG_DIR="${HOME}/.anysphere/cache/logs"
	create_user_dir "${HOME}/.anysphere"
	create_user_dir "${HOME}/.anysphere/cache"
	create_user_dir "${HOME}/.anysphere/cache/logs"
fi

exec 2>&1 >"$LOG_DIR"/postinstall.log

echo "hello from anysphere postinstall script!"

INSTALL_DIR=$2

PLIST="$(
	cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>co.anysphere.anysphered</string>
    <key>Program</key>
    <string>$INSTALL_DIR/Anysphere.app/Contents/Resources/anysphered</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
	<true/>
    <key>StandardOutPath</key>
    <string>$LOG_DIR/anysphered.log</string>
    <key>StandardErrorPath</key>
    <string>$LOG_DIR/anysphered.err</string>
</dict>
</plist>
EOF
)"

# launch as user
uid=$(id -u "$USER")
echo "user: $USER, uid: $uid"
PLIST_PATH="/Library/LaunchAgents/co.anysphere.anysphered.plist"
echo "$PLIST" >"$PLIST_PATH"
chmod 644 "$PLIST_PATH"
# if already existed, unload
launchctl asuser "$uid" launchctl unload "$PLIST_PATH"
launchctl asuser "$uid" launchctl load "$PLIST_PATH"

mkdir -p /usr/local/bin
ln -sf "$INSTALL_DIR/Anysphere.app/Contents/Resources/anysphere" /usr/local/bin/anysphere
