image:
  file: .gitpod.Dockerfile
tasks:
  - name: Prepare Bazel
    before: "./gitpod-init.sh"
    init: git submodule update --init --recursive --force third_party/SEAL && bazel build //... && bazel build //... -c dbg && bazel build //... -c opt
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080 # VNC for X11 C++ GUI Development
    onOpen: open-preview

vscode:
  extensions:
    - ms-vscode.cpptools
    - github.copilot
    - galexite.bazel-cpp-tools
    - bazelbuild.vscode-bazel
    - ms-vscode.cpptools-extension-pack
    - hashicorp.terraform
    - Guyutongxue.cpp-reference
