image:
  file: .gitpod.Dockerfile
tasks:
  - name: Prepare Bazel
    init: ./setupgit.sh && ./gitpod-init.sh && ./build-all.sh
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080 # VNC for X11 C++ GUI Development
    onOpen: open-preview

vscode:
  extensions:
    - ms-vscode.cpptools
    - github.copilot
    - galexite.bazel-cpp-tools
    - bazelbuild.vscode-bazel
    - ms-vscode.cpptools-extension-pack
    - hashicorp.terraform
    - Guyutongxue.cpp-reference
    - dbaeumer.vscode-eslint
    - zxh404.vscode-proto3
    - esbenp.prettier-vscode
    - bradlc.vscode-tailwindcss
    - visualstudioexptteam.vscodeintellicode
    


