#
# Copyright 2022 Anysphere, Inc.
# SPDX-License-Identifier: MIT
#

cc_library(
    name = "nonprivate_pir_lib",
    srcs = ["nonprivate_pir.cc"],
    hdrs = ["nonprivate_pir.hpp"],
    linkstatic = True,
    visibility = ["//visibility:public"],
    deps = [
        "//asphr/asphr:asphr_lib",
    ],
)
