cc_library(
    name = "nonprivate_pir_lib",
    srcs = ["nonprivate_pir.cc"],
    hdrs = ["nonprivate_pir.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//asphr:asphr_lib",
    ],
)
