load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "examples",
    srcs = [
        "1_bfv_basics.cc",
        "2_encoders.cc",
        "3_levels.cc",
        "4_ckks_basics.cc",
        "5_rotation.cc",
        "6_serialization.cc",
        "7_performance.cc",
        "examples.cc",
        "examples.h",
    ],
    deps = [
        "@seal",
    ],
)
